
### 1. Register user baru
POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "rahasia",
  "name": "test"
}

###

### 2. Login user (dapatkan token)
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "rahasia"
}

###


### 3. Get current user (pakai token dari login)
GET http://localhost:3000/api/users/current
Authorization: 0bff5b37-710f-4cbf-8724-fc08aa93ca45
Accept: application/json

###
### 4. Update user

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Authorization: 0bff5b37-710f-4cbf-8724-fc08aa93ca45
Accept: application/json

{
  "name": "test",
  "password": "rahasiaBaru"
}

###
