
### 1. Register user baru
POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "rahasia",
  "name": "test"
}

###

### 2. Login user (dapatkan token)
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "rahasia"
}
