
### 1. Register user baru
POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "rahasia",
  "name": "test"
}

###

### 2. Login user (dapatkan token)
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "rahasia"
}

###


### 3. Get current user (pakai token dari login)
GET http://localhost:3000/api/users/current
Authorization: a8293c18-624b-47fb-aab6-a1c435c230c5
Accept: application/json

###

